name: Building xml file at /static/feed.xml
on:
  schedule:
    - cron: "0 */1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
      - name: Installing deps
        run: npm install
      - name: Running xml build
        run: npm run rss
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updates rss feed file
